import Foundation
import CircuiteFoundation

public enum TapeoutArtifactGenerationError: Error, Sendable, Hashable, LocalizedError {
    case invalidStreamOutRequest(String)
    case invalidPersistenceTarget(String)
    case persistenceFailed(String)
    case persistedArtifactMismatch(String)
    case persistedArtifactUnreadable(String)

    public var errorDescription: String? {
        switch self {
        case .invalidStreamOutRequest(let reason):
            "The stream-out generation request is invalid: \(reason)"
        case .invalidPersistenceTarget(let reason):
            "The immutable artifact target is invalid: \(reason)"
        case .persistenceFailed(let reason):
            "Immutable artifact persistence failed: \(reason)"
        case .persistedArtifactMismatch(let reason):
            "The persisted artifact does not match the generated bytes: \(reason)"
        case .persistedArtifactUnreadable(let reason):
            "The persisted artifact could not be reloaded: \(reason)"
        }
    }
}
